assets/js/events.js
http://strangewill.github.io/events/
Ta-da.
=> Handles GAPI returning undefined event descriptions.

assets/js/events.js, css/layout/_events.scss
This is just a fix to display everything with the correct timezone.  I also noticed that some of the paddings can cause weird overflows so I updated that as well.
=> Fix timezone issues and padding for events

_devs/southerneer.md
First pull request here. Hopefully I didn't screw anything up.
=> added southerneer to the developers list

_devs/jdballard.md
=> Added my SO account

groups.html
I broke this with the last PR… Sorry folks :sob:
=> fix broken image paths

_devs/adamcofer.md
=> chadevs+=adamcofer

_devs/charlesfannin.md
adds charlesfannin.md to _devs
=> adds charlesfannin.md to _devs

_devs/charlesfannin.md
fixes site url for charlesfannin.md
=> fixes site url for charlesfannin.md

_devs/calebalbritton.md
=> gravatar is not a thing

_devs/calebalbritton.md
this should fix the icon that's broken, but I still hate gravatar.
=> fixed link

_devs/calebalbritton.md
turns out it's just an md5 hash of the email address.
=> added my gravatar id

_devs/bobbyburden.md
Yay, typo in commit message...
=> Add myself to the devs list.

_layouts/default.html, assets/sass/layout/_footer.scss, assets/sass/layout/_main.scss
=> Fixes #131

_devs/davdunc.md
Update to add davdunc to _devs.
=> add davdunc to _devs

_devs/auximage.md
=> Adding myself

_devs/timcoy.md
Adding myself as a local developer.
=> Add Tim Coy

_devs/t-richards.md
Adds Tom Richards to the list-o'-devs.
=> Yet another addition to the devs list

_devs/williamroush.md
=> Add StackOverflow to William Roush

speaking.html
Please review these general guidelines for our AV system, hopefully to mitigate some of the last minute scramble to make things work for speakers.
=> added general technical guidelines for speakers

_devs/mikeconrad.md
Signed-off-by: Mike Conrad <mike@enxo.co>
=> Adding myself to the list.

_devs/matzko.md
I'm a developer living and working in Chattanooga, so please add me to the list!
=> Adding Austin Matzko to chadevs list of developers

_devs/johncotton.md
Add new profile(John Cotton) to the /devs page.
=> Add John Cotton to _devs

_devs/nbranch.md
Just adding myself to the devs page
=> Adding Noah Branch to list

_devs/willamin.md
=> Add myself to the devs list

live.html
=> Update iframe to link to live stream

_templates/kf.md
=> added kf.md for inclusion in chatdev page

_devs/joehdodd.md
Hi All 👋. I've been in the Slack workspace for a bit, so I felt like I should finally add my info to appear on the website. Thanks!
=> add dev joehdodd

_config.yml
(It links back to the COC, and requires you to check a box agreeing to it to sign up.)
=> Point slack link to Slackin

_devs/moegreen.md
=> add moegreen to _devs
